import Navbar from "@/components/Navbar"
import './globals.css'
import Footer from "@/components/Footer"


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout=({ children })=> {
  return (
   <div className="container mx-auto">
<Navbar></Navbar>
{children}
<Footer/>
   </div>
  )
}

export default RootLayout
